name: publish to gh pages
on:
  push:
    paths:
    - 'docs/**'
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs pymdown-extensions mkdocs-material
    - name: Build
      run: |
        mkdocs build
        mkdir -p out/docs
        mv site/* out/docs
        mv docs/CNAME out
        mv docs/charts out
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./out
